# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

COPY . .

EXPOSE 3000

# Start the application
CMD ["node", "server.js"]
