version: '3'
services:
  backend:
    build: ./backend
    restart: always
    container_name: backend_container
    ports: 
      - "5000:5000"
    environment:
      - LOCAL_HOST=http://localhost
      - PORT=5000

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports: 
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost
      - PORT=5000
    volumes:
      - ./node_modules:/app/node_modules
